// <auto-generated />
namespace Giessformkonfigurator.WPF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changedvererbungoncomponents : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedvererbungoncomponents));
        
        string IMigrationMetadata.Id
        {
            get { return "202110041208258_changed vererbung on components"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
