// <auto-generated />
namespace Gießformkonfigurator.WPF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changedprecisionofdecimalonproductsfactorPU : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedprecisionofdecimalonproductsfactorPU));
        
        string IMigrationMetadata.Id
        {
            get { return "202109220948322_changed precision of decimal on products factor PU"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
