// <auto-generated />
namespace Gießformkonfigurator.WPF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ProductchangesAddedSingleMoldTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProductchangesAddedSingleMoldTables));
        
        string IMigrationMetadata.Id
        {
            get { return "202109220934549_Product changes, Added SingleMold Tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
